import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "../components/Footer";
import Exite from "../components/modals/Exite";
import ModalProvider from "@/context/ModalProvider";
import NavBar from "@/components/Navbar";
import DetailsInfoProvider from "@/context/CardDetailsInfoProvidre";
import StoreProvider from "./StoreProvider";
import { makeStore } from "@/lib/store";
const mullerLight = localFont({
  src: "../fonts/Mullerlight.ttf",
  variable: "--Mullerlight",
  weight: "100 900",
});

const muller = localFont({
  src: "../fonts/Muller.ttf",
  variable: "--Muller",
  weight: "100 900",
});

const mullerBold = localFont({
  src: "../fonts/MullerBold.ttf",
  variable: "--MullerBold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${muller.variable}  ${mullerBold.variable} antialiased`}
      >
        <StoreProvider>
          <ModalProvider>
            <DetailsInfoProvider>
              <NavBar />
                {children}
              <Footer />
            </DetailsInfoProvider>
          </ModalProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
